# Generated by Django 3.1.6 on 2021-02-17 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_number', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('id_type', models.CharField(choices=[('National_ID', 'National_ID'), ('Passport', 'Passport')], default='', max_length=20)),
                ('hire_date', models.DateTimeField()),
                ('social_status', models.CharField(choices=[('Single', 'Single'), ('Maried', 'Maried')], default='', max_length=20)),
                ('date_birth', models.DateTimeField()),
                ('blace_birth', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('idd', models.CharField(max_length=50)),
                ('insured', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('has_medical', models.BooleanField()),
                ('leaves_balance', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('Casual', 'Casual'), ('trainee', 'trainee'), ('Contractors', 'Contractors')], default='', max_length=20)),
                ('contract_start', models.DateTimeField()),
                ('contract_end', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='employees.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.position')),
            ],
        ),
    ]
