# Generated by Django 3.1.6 on 2021-02-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210217_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
