# Generated by Django 3.1.6 on 2021-02-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual', 'Casual'), ('Annual', 'Annual')], default='', max_length=20)),
                ('leave_value', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='All_Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start', models.DateTimeField()),
                ('leave_end', models.DateTimeField()),
                ('resume_date', models.DateTimeField()),
                ('Status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Waiting to approve', 'Waiting to approve')], default='', max_length=20)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.leave_master')),
            ],
        ),
    ]
