# Generated by Django 3.1.6 on 2021-02-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_leaves',
            name='leave_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='all_leaves',
            name='leave_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='all_leaves',
            name='resume_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave_master',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Annual', 'Annual'), ('Sick', 'Sick')], default='', max_length=20),
        ),
    ]
