# Generated by Django 3.1.6 on 2021-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_auto_20210215_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_leaves',
            name='leave_reason',
            field=models.CharField(default=0.0004950495049504951, max_length=200),
            preserve_default=False,
        ),
    ]
