# Generated by Django 3.1.6 on 2021-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_all_leaves_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_leaves',
            name='number_of_days',
            field=models.CharField(default=0.0004950495049504951, max_length=2),
            preserve_default=False,
        ),
    ]
