# Generated by Django 3.1.6 on 2021-02-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_all_leaves_number_of_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_leaves',
            name='number_of_days',
        ),
    ]
