# Generated by Django 3.1.6 on 2021-02-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_auto_20210217_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_leaves',
            name='Status',
            field=models.CharField(default='WAITING FOR APPROVE', max_length=20),
        ),
    ]
