# Generated by Django 3.1.6 on 2021-02-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20210218_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
